sudo: false

branches:
  only:
  - master

cache:
  npm: true

notifications:
  email: false

matrix:
  fast_finish: true
  include:
    - name: Check i18n and build output
      language: node_js
      node_js: '10'
      script:
        - .travis/check-i18n.sh
        - .travis/build-output.sh
